---
# yaml format
all:
  children:
    routers:
      hosts:
        192.168.122.10:
        192.168.122.11:
      vars:
        ansible_network_os: ios # junos, iosxr, asa
        ansible_user: randy
        ansible_password: test
        ntp_server1: "192.0.2.1"
        ntp_server2: "192.0.2.2"
